### ISSUE TITLE
GS308EPP

### ISSUE THREAD

**Issue by davidk** [nitram509/ntgrrc#2]
Hello,

I was able to test against a GS308EPP and I can confirm that everything works as expected:

PoE status:

```
Port ID |       Status | PortPwr class | Voltage (V) | Current (mA) | PortPwr (W) | Temperature (°C) | Error status
      1 | Delivering Power |             4 |          53 |          196 |   10.500000 |               33 | No Error
      2 |    Searching |               |           0 |            0 |    0.000000 |               33 | No Error
      3 | Delivering Power |             3 |          52 |           34 |    1.800000 |               33 | No Error
      4 |     Disabled |               |           0 |            0 |    0.000000 |               33 | No Error
      5 |     Disabled |               |           0 |            0 |    0.000000 |               33 | No Error
      6 |     Disabled |               |           0 |            0 |    0.000000 |               33 | No Error
      7 |     Disabled |               |           0 |            0 |    0.000000 |               33 | No Error
      8 |    Searching |               |           0 |            0 |    0.000000 |               33 | No Error
```

PoE settings:

```
Port ID | Port Power |        Mode | Priority | Limit Type | Limit (W) |                 Type
      1 |    enabled |     802.3at |      low |       user |      30.0 |             IEEE 802
      2 |    enabled |     802.3at |      low |       user |      30.0 |             IEEE 802
      3 |    enabled |     802.3at |      low |       user |      30.0 |             IEEE 802
      4 |   disabled |     802.3at |      low |       user |      30.0 |             IEEE 802
      5 |   disabled |     802.3at |      low |       user |      30.0 |             IEEE 802
      6 |   disabled |     802.3at |      low |       user |      30.0 |             IEEE 802
      7 |   disabled |     802.3at |      low |       user |      30.0 |             IEEE 802
      8 |    enabled |     802.3at |      low |       user |      30.0 |             IEEE 802
```

I had hoped to control the PoE power state for each port, but saw that it was missing. Are you open to accepting a PR to add the functionality? I believe I have the basics ready, but it would likely need some more integration to fit.

**Comment by nitram509** [comment]
Hi David,

thank you very much for providing this feedback.
I would be glad if you open a PR.

May I ask, what firmware you 308EEP run on?
I did start to make a table of compatibility in the main README.

May I add some guidance words...
* in the test-data folder, I did add the HTML responses, files named by each endpoint.
* about the test files, I would love to see a subfolder, e.g. GS308xxx and GS305xxx to have multiple test files - this will ensure we have enough regression safety when we optimize the parsers
* for setting the ports, I already thought about it, and it would be nice to set one or multiple ports with a single command
   * I would appreciate we have a little dialog/chat about how the parameter will look like, before implementation.

Overall, thank you very much (in advance) for contributing :)

**Comment by davidk** [comment]
The firmware version of the GS308EPP that I was running against was the latest for the model -- `V1.0.0.10`. I did get to test this before on the prior version, `V1.0.0.8` as well, without issue..

- I'd be happy to contribute test-data samples matching the ones currently in the repository (as well as one for the PoE power test where it needs to supply a hash as a part of the POST request). I will open a pull to track and introduce the ones not related to the power feature.

- Regarding PoE port power and the UX behind it, I did a quick mock up as it was easy, but had other ideas as well:

```
$ ./ntgrrc poe set -a 192.168.1.240 -p 1 -p 3 --power=false
SUCCESS
SUCCESS
```

- Would it be preferable to use something like `-p 1:on -p 3:off` instead? 

- `--power=true` and `--power=false` are also quite unwieldy. Could these be something like `--no-power` and `--power` instead or changed for an alternative?

**Comment by nitram509** [comment]
Hi David,

good thoughts you started with.

I like the ```-p 1 -p 3``` approach, as it would allow multiple ports to set at once

about the settings I thought symmetry would ease the usage.

if this is given:
| Port ID | Port Power | Mode    | Priority | Limit Type | Limit (W) | Type     |
|---------|------------|---------|----------|------------|-----------|----------|
| 1       | disabled   | 802.3at | low      | user       | 30.0      | IEEE 802 |

then the options (long name) would look like (equal sings are optional, a blank should work as well)
 
* -- power disabled   
* --mode 802.3ar
* --priority high
* -- limit 10
* -- type "IEEE 802"

----

also, in the response, the two SUCCESS messages do lack correlation to the port index.
I propose using a similar result table , as it's used in the show settings command.
In the above example, this could look like ... (the columns port power was changed)
```markdown
| Port ID | Port Power | Changed?                  |
|---------|------------|---------------------------|
| 1       | disabled   | success                   |
| 3       | disabled   | error: connection timeout |
```

**Comment by nitram509** [comment]
btw. no pressure on the PR ... 
I'm used to look into the future, and drawing big pictures :)
And I'm always in, to implement "minimum viable features" as in agile best practice :)

Thank you very much for your efforts.

**Comment by nitram509** [comment]
Merged.
Thank you @davidk for your contribution.
