### ISSUE TITLE
Possibility of reading/writing port speed for testing network connect/disconnect for non-poe devices

### ISSUE THREAD

**Issue by hackboxguy** [nitram509/ntgrrc#37]
Dears,
Thanks for this nice tool for controlling low cost POE switches via CLI.

Here is my wish to enhance this tool further:
Using webUI, I was able to turn OFF the network communication(to a non-poe-device) by setting the speed as Disable. When speed was changed to Auto, communication with non-poe-device started again.

Would be nice to have this possibility to enablin/disablin ports using ntgrrc command.. eg:
Port1 Disable : ./ntgrrc switch set -p1 --speed disable --address 192.168.x.y
Port1 Enable : ./ntgrrc switch set -p1 --speed auto --address 192.168.x.y

![image](https://github.com/nitram509/ntgrrc/assets/1315947/f4d426ee-eed1-4b1f-bf8e-33057aee2671)

**Comment by davidk** [comment]
Hello, thank you for the feature request. The implementation ended up being slightly different to match with the `poe` command and is now available as a part of: [v0.9.0](https://github.com/nitram509/ntgrrc/releases/tag/v0.9.0). Here is the help output for `port set`:

```
set properties for a port number

Flags:
  -h, --help                         Show context-sensitive help.
      --help-all                     advanced/full help
  -v, --verbose                      verbose log messages
  -q, --quiet                        no log messages
  -f, --output-format="md"           what output format to use [md, json]
  -d, --token-dir=""                 directory to store login tokens

  -a, --address=STRING               the Netgear switch's IP address or host name to connect to
  -p, --port=PORT,...                port number (starting with 1), use multiple times for setting multiple ports at once
  -n, --name=STRING                  sets the name of a port, 1-16 character limit
  -s, --speed=STRING                 set the speed and duplex of the port ['100M full', '100M half', '10M full', '10M half', 'Auto', 'Disable']
  -i, --ingress-rate-limit=STRING    set an incoming rate limit for the port ['1 Mbit/s', '128 Mbit/s', '16 Mbit/s', '2 Mbit/s', '256 Mbit/s', '32 Mbit/s', '4 Mbit/s', '512 Kbit/s', '512 Mbit/s',
                                     '64 Mbit/s', '8 Mbit/s', 'No Limit']
  -o, --egress-rate-limit=STRING     set an outgoing rate limit for the port ['1 Mbit/s', '128 Mbit/s', '16 Mbit/s', '2 Mbit/s', '256 Mbit/s', '32 Mbit/s', '4 Mbit/s', '512 Kbit/s', '512 Mbit/s',
                                     '64 Mbit/s', '8 Mbit/s', 'No Limit']
      --flow-control=STRING          enable/disable flow control on port ['Off', 'On']
```
