### ISSUE TITLE
Trying with GS316EP but fails at login

### ISSUE THREAD

**Issue by jsanchez73** [nitram509/ntgrrc#56]
Hello,

Looking forward to be able to use this application on my GS316EP (firmware 1.0.2.6) switch.

I assumed that it would work since the similar GS308EP has been successfully tested (though with a different firmware version), but so far it fails at login with error:

Error: random seed value not found in login.cgi response. An element with id=rand and an attribute 'value' is expected

This happens both in Windows 10Pro and Raspberry pi running Raspbian GNU/Linux 10 (buster).

Any idea of what could be the problem?

Thanks in advance,

Jose

P.S: I tried to reach http://switchipaddrr/login.cgi and I get 404 error as if there was no such path anymore

**Comment by jsanchez73** [comment]
Sorry, forgot to mention I am running it on Windows 10 Pro version 22H2

**Comment by nitram509** [comment]
Hi Jose,

unfortunately, I don't own a GS316EP to test on my own, but if you have some time and could support us we might make this happen.

What I'm seeking for, is the source data of the login page, first.
If you could do your "regular" login to the router via e.g. Chrome browser,
then open the developer tools in Chrome, go to network tab, and look for the login page.
Once you found it, please send us the response of that page (2).
We store this information here in the repository in the test-data folder - you can check out for the other models.
Also, we need the request URL (1)

In case you never worked with Chrome developer tools, here's a video explaining it:
https://www.youtube.com/watch?v=kPe3wtA9aPM

* (2) At the time mark: 2:27, you'll see the response HTML data -> this is what I'm looking for, but from the login page.
* (1) At the time mark: 3:27, you'll see the request URL -> this one for the login page we need as well.

If this works for you and you could provide us this data, we could try to make a pre-release for you.

Regards
Martin

**Comment by jsanchez73** [comment]
Hello Martin,

Thanks a lot for your quick reply. Is this what you need?
![image](https://github.com/nitram509/ntgrrc/assets/78077173/06018467-7f96-4acb-9d0b-426eaafd08de)
https://www.dropbox.com/scl/fi/47r4pmo7cwuwbkqgl75xo/login.html?rlkey=7yw3eqbowuvn471mtgbtd6t9d&dl=0

Hope it helps. Best Regards,

Jose

**Comment by nitram509** [comment]
Hello Jose,

I did a brief test, and it seems the content of the login is almost the same, but the URLs changed.
Are you able to pull go source code, compile it and try it on your box?
IF so, I could prepare some code and you could try it.
Else, it might be a bit more challenge to prepare a pre-compile test version for you.

**Comment by nitram509** [comment]
FYI: I did create a new feature branch https://github.com/nitram509/ntgrrc/tree/gs316ep-support

/cc @davidk FYI

**Comment by jsanchez73** [comment]
Hello Martin,

I have never compiled Go code, but have done it with other languages. So I'll be happy to give it a try. Best Regards,

Jose

**Comment by nitram509** [comment]
> Hello Martin,
> 
> I have never compiled Go code, but have done it with other languages. So I'll be happy to give it a try. Best Regards,
> 
> Jose

Awesome.
I've adopted the login to what I got from your screenshot.
Just check out the above branch, install go and fire a `go build` in the main folder.
That should produce the ntgrrc.exe for you.

I hope the login works with that change
and the other settings did not have changed, so parameters still work.

**Comment by jsanchez73** [comment]
Great, I'll give it a go tomorrow :)

**Comment by jsanchez73** [comment]
Hello Martin,

I compiled the gs316ep branch and tried it from my raspberry pi. I get the following error if I run login with the verbose flag:

fetch seed value from: http://192.168.0.69/wmi/login
200 OK
login attempt: http://192.168.0.69/redirect.html
200 OK
Error: login request returned 200 OK, but response did not contain a session token (SID cookie value#). this is known behaviour from the switch. please, wait some minutes and tray again later


It seems that this version of ntgrrc is looking for the token in the SID cookie. I checked after login in via the browser and it generated this cookie:

![image](https://github.com/nitram509/ntgrrc/assets/78077173/a3740bcb-9eb1-4025-a94e-a0ac77413969)

Hope this helps,

Jose

**Comment by jsanchez73** [comment]
Martin,

I am sending also the homepage.html where I land after login in.
https://www.dropbox.com/scl/fi/jh8rd0nbjsyzntpc6glam/homepage.html?rlkey=oi695otvzuqisshdw6v1ls2kz&dl=0
Here's the screenshot of the homepage.html Cookies tab:
![image](https://github.com/nitram509/ntgrrc/assets/78077173/0e5643d9-198c-4365-a7f2-2670001eaf6b)
and the Initiator tab:![image](https://github.com/nitram509/ntgrrc/assets/78077173/fcdc4e76-f6ac-46f0-af48-bf307e040478)
Hope this helps,

Jose

**Comment by nitram509** [comment]
Jose, 

thanks for sharing the details, that's exactly what I need.
I did change the logic for the login ... that should work now ... `./ntgrrc login --address IPADDRESS`

It seems Netgear has changed some page names (URLs), like the other settings stuff will not work yet.
I hope, they have at least kept the page structure equal.

These are the pages we use ... what are the equivalents?
* /getPoePortStatus.cgi
* /PoEPortConfig.cgi
* /dashboard.cgi
* /port_status.cgi

Could you provide the equivalents, please?

**Comment by jsanchez73** [comment]
Thanks a lot Martin. I´ll try with these changes. If it logins I'll try the rest of the functionality and if it fails I'll look for the equivalents to the ones you are currently using. Best Regards,

Jose

**Comment by nitram509** [comment]
Jose,

I'm already thinking, how to integrate this into the main branch.
Problem: GS30x and GS316 use different login URLs.
Idea: request `/` first and depending on the response, detect the switch type.
This would be an auto-detection for the switch type and most convinient for the users.
In the worst case, I have to implement a mandatory command line parameter to select the model.

I have this idea for auto-detection:
<img width="773" alt="Screenshot 2024-03-21 at 23 22 56" src="https://github.com/nitram509/ntgrrc/assets/1189394/f937ca55-5c2b-40ef-91c1-3dc7cf15a498">

IF the switches somehow react differently and predictable when requesting `/` then I could derive the switch type from that and store this into the session token.
May I ask, you couls also share the HTTP Response header, when calling / , please?

@davidk May I ask you as well, if you could test how the 308 model responds? (because I have no netgear at hand.)

**Comment by crypto-smoke** [comment]
As a new owner of a GS316EPP, I'm excited to see this support being added. I think a good way to move forward without making life too painful is to refactor this into separate packages depending on router model. This has the bonus of making life easy for myself, because I want to integrate this into my own projects as a library. I don't need full management remotely, I just want to be able to toggle port poe power :)

**Comment by davidk** [comment]
> @davidk May I ask you as well, if you could test how the 308 model responds? (because I have no netgear at hand.)

Hi Martin! The GS308EPP responds to a request at / with a redirect to `login.cgi`, with content:

```
> GET / HTTP/1.1
> Host: gs308epp
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: text/html
< Cache-Control: no-cache
< Expires: -1
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< 
<html>
<head>
<title>Redirect to Login</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="/style.css">
<script type="text/javascript" language="JavaScript">
	top.location.href = "/login.cgi";
</script>
</head>
<body>
</body>
</html>
```

The network panel for the same request (with options on to try and preserve the request to /, otherwise it gets squashed down to `login.cgi`):
![gs308epp](https://github.com/nitram509/ntgrrc/assets/36493/57cac480-3901-4a5b-baa2-82d32df39cab)

As usual, please let me know if you need any more information

**Comment by jsanchez73** [comment]
> IF the switches somehow react differently and predictable when requesting `/` then I could derive the switch type from that and store this into the session token. May I ask, you couls also share the HTTP Response header, when calling / , please?

Hello Martin. When requesting `/` this is what I get:
![image](https://github.com/nitram509/ntgrrc/assets/78077173/414d25fc-f03b-4e7d-b793-d6474db3b936)

and this is the response:

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Pragma" content="no-cache">
<title>NETGEAR  GS316EP</title>
<link rel="stylesheet" type="text/css" href="/loginPage.css">
<!LANGUAGE_SCRIPT_TYPE_KEY>
<script src="/jquery.min.js" type="text/javascript"></script>
<script src="/jquery_migrate_min.js" type="text/javascript"></script>
<script src="/jquery.md5.js" type="text/javascript"></script>
<script src="/loginPage.js" type="text/javascript"></script>
<script type='text/javascript' language='JavaScript'>
function submitLogin()
{
    encryptPwd();
    document.forms[0].submit();
	return true;
}
function onEnterSub(e)
{
	var whKey;
	
	if (window.event)
	{
		whKey = e.keyCode;
	}
	else if (e.which)
	{
		whKey = e.which;
	}
	
	if(whKey == '13')
	{
		submitLogin();
	}
}
</script>
</head>
<body id="loginBody">
<form name="login" method="post" onSubmit="return false;" action="/redirect.html" autocomplete="off">
    <input type="hidden" id="submitPwd" name="LoginPassword" value="">
<div id="loginWrapper">
	<div class="netgearLogo" style="height:214px;">
		<a href="http://www.netgear.com/" target="_blank">
			<img src="/switch_logo_login.svg" style="border:none;">
		</a>
		<span class="p-name">GS316EP</span>
	</div>
	<div class="summary" style="width:85%;"><span class="lang">If logging in for the first time, log in with your switch's default password which is found on the label on the bottom of the switch.</span></div>
	<div id="passwordWrapperdiv" class="passwordWrapper">
		<div id="loginPasswordDiv" class="input-wrapper ng-init-block">

				<div class="input-title editHead active lang">Password</div>
				<input id="Password" class="editBody wideInput" type="password" value="" maxlength="20" onkeypress="onEnterSub(event);" autocomplete="off">
				<div onclick="toggleEye()" class="switch-eye">
			        <i class="icon-eye-off show"></i>
			        <i class="icon-eye-on"></i>
			    </div>
				<input type="hidden" id='rand' value="885340480" disabled>
				<span id="loginPageErrorMsg" class="validationRed"></span>

		</div>
	</div>

	<div class="loginButton modalFooterBlockOne apply waves-effect waves-gray btn">
		<div class="btnWrapper" onclick="submitLogin()">
			<a class="lang">LOG IN</a>
		</div>
	</div>
</div>
</form>
</body>
</html>

I have just tried the version with the last modifications but get the same error as with the previous version:

fetch seed value from: http://192.168.0.69/wmi/login
200 OK
login attempt: http://192.168.0.69/redirect.html
200 OK
Error: login request returned 200 OK, but response did not contain a session token (SID cookie value#). this is known behaviour from the switch. please, wait some minutes and tray again later

I´ll post later a dropbox link with the equivalent pages for PortStaus, PortConfig, etc...

Best Regards,

Jose

**Comment by nitram509** [comment]
> Hello Martin. When requesting `/` this is what I get: ...

Unfortunately, that's not yet all the information I need.

May I ask, you could send me a "curl" response, please?
On a Raspi, it's likely already present ... or simply install it via `sudo apt-get install curl`

E.g. when you open a command prompt, and fire this command:
```shell
curl -v http://IPADDRESS/
```

That response is more condensed and would reveal the same detail as from David's response above, which is more in depth helpful to compare each other.

Thank you in advance.

**Comment by nitram509** [comment]
> As a new owner of a GS316EPP, I'm excited to see this support being added. I think a good way to move forward without making life too painful is to refactor this into separate packages depending on router model. This has the bonus of making life easy for myself, because I want to integrate this into my own projects as a library. I don't need full management remotely, I just want to be able to toggle port poe power :)

Hi Smoke,
thank you for your positive words.
Please, feel invited to contribute to this group/repo as well - you're very welcome.
Also, if you could spend some time on testing this bleeding edge development, this is very helpful,
as this makes the result more robust.

**Comment by jsanchez73** [comment]
> ```shell
> curl -v http://IPADDRESS/
> ```

Hello Martin,

Here's the curl response:

> GET / HTTP/1.1
> Host: 192.168.0.69
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: text/html
< Cache-Control: no-cache
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< 
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Pragma" content="no-cache">
<title>NETGEAR  GS316EP</title>
<link rel="stylesheet" type="text/css" href="/loginPage.css">
<!LANGUAGE_SCRIPT_TYPE_KEY>
<script src="/jquery.min.js" type="text/javascript"></script>
<script src="/jquery_migrate_min.js" type="text/javascript"></script>
<script src="/jquery.md5.js" type="text/javascript"></script>
<script src="/loginPage.js" type="text/javascript"></script>
<script type='text/javascript' language='JavaScript'>
function submitLogin()
{
    encryptPwd();
    document.forms[0].submit();
	return true;
}
function onEnterSub(e)
{
	var whKey;
	
	if (window.event)
	{
		whKey = e.keyCode;
	}
	else if (e.which)
	{
		whKey = e.which;
	}
	
	if(whKey == '13')
	{
		submitLogin();
	}
}
</script>
</head>
<body id="loginBody">
<form name="login" method="post" onSubmit="return false;" action="/redirect.html" autocomplete="off">
    <input type="hidden" id="submitPwd" name="LoginPassword" value="">
<div id="loginWrapper">
	<div class="netgearLogo" style="height:214px;">
		<a href="http://www.netgear.com/" target="_blank">
			<img src="/switch_logo_login.svg" style="border:none;">
		</a>
		<span class="p-name">GS316EP</span>
	</div>
	<div class="summary" style="width:85%;"><span class="lang">If logging in for the first time, log in with your switch's default password which is found on the label on the bottom of the switch.</span></div>
	<div id="passwordWrapperdiv" class="passwordWrapper">
		<div id="loginPasswordDiv" class="input-wrapper ng-init-block">

				<div class="input-title editHead active lang">Password</div>
				<input id="Password" class="editBody wideInput" type="password" value="" maxlength="20" onkeypress="onEnterSub(event);" autocomplete="off">
				<div onclick="toggleEye()" class="switch-eye">
			        <i class="icon-eye-off show"></i>
			        <i class="icon-eye-on"></i>
			    </div>
				<input type="hidden" id='rand' value="885340480" disabled>
				<span id="loginPageErrorMsg" class="validationRed"></span>

		</div>
	</div>

	<div class="loginButton modalFooterBlockOne apply waves-effect waves-gray btn">
		<div class="btnWrapper" onclick="submitLogin()">
			<a class="lang">LOG IN</a>
		</div>
	</div>
</div>
</form>
</body>
</html>

Best Regards,

Jose

**Comment by nitram509** [comment]
@davidk Aus usual, thank you very much for your support. 👍🚀

All, just wanna share some idea moving forward with this new model support.
Any feedback of yours is welcome - as I don't have a netgear switch at hand, I appreciate our group and collaboration very much. That's what I love about Open Source :)

Ideas:
* make ntgrrc auto-detect the model, as mentioned above (so far it looks, like we can make this happen)
* add optional "-force-model" CLI switch, to override the auto-detection
* add more verbose messages, which might later help in analysing issues.
* once the login succeeded, store the model information in the session token file as well == this preserves model information for later commands
* extend the unit test code, to test for different model responses - you can already see that in login_test.go (parameter tests)

So far, ntgrrc was not designed as library ... @crypto-smoke if you have some feedback when using ntgrrc as a lib, please share as well - I believe we can make both options possible.

If you want to contribute code ... I propose smaller PRs, based on the branch `gs316ep-support`.

This is a great momentum we have here. 😀

**Comment by nitram509** [comment]
@jsanchez73 thanks for the curl output.
So I see and conclude, the response looks quite different and we simply might use the `<title>NETGEAR GS316EP</title>` as string to detect this model. 👍

**Comment by nitram509** [comment]
@crypto-smoke Huh, I just realize you're writing 'GS316EPP' ... which is somewhat different than 'GS316EP' 👍
May I ask, please provide the responses from above as well, so we can extend the test-files, please - that would be awesome.

**Comment by crypto-smoke** [comment]
```
> GET / HTTP/1.1
> Host: 192.168.1.224
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: text/html
< Cache-Control: no-cache
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff```


[root.txt](https://github.com/nitram509/ntgrrc/files/14726977/root.txt)

**Comment by nitram509** [comment]
Basic support just released with https://github.com/nitram509/ntgrrc/releases/tag/v0.10.0
