### ISSUE TITLE
Support POE reset, for Netgear 16 port switch

### ISSUE THREAD

**Issue by electron1963** [nitram509/ntgrrc#70]
Have been using the project for a Netgear 8 port switch - works great,  Would like to inquire into support of the 16 port version of this switch

**Comment by nitram509** [comment]
As discussed, please join the Slack channel, so we can streamline the development.
https://join.slack.com/t/nitram509/shared_invite/zt-2qvxx4kur-FvIOJH7WW9MBK_iheWVyGw

PS: this link is only valid for 7 days.
